[package]
authors = [
  "Adam Spofford <pieflavor.mc@gmail.com>" ,
  "Hunar Roop Kahlon <hunar.roop@gmail.com>"
]
name = "opm"
version = "0.1.0"

[dependencies]
clap = "*"
flexi_logger = "*"
hyper = "*"
log = "*"
json = "*"
